{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a44c8810-3cf6-4f8b-a537-0d5b96592ab7",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: Explain why we have to use the Exception class while creating a custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "Answer: custom exceptions enhance the usabillity of a class. An exception class should have init and str magic methods which are called automatically during the\n",
    "exception handling process."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f9614a8-201f-4dd3-b85b-3aef75fe9148",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: Write a python program to print Exception Hierarchy.\n",
    "Answer: \n",
    "#Inbuilt exceptions:\n",
    "#Import the inspect module\n",
    "import inspect as ipt\n",
    "def tree_class(cls, ind = 0):\n",
    "    print('-' * ind, cls.__name__)\n",
    "    for K in cls.__subclasses__():\n",
    "        tree_class(K, ind+3)\n",
    "print(\"Inbuilt exception is:\")\n",
    "#The inspect.getmro() will return the tuple.\n",
    "#of class which is cls's base classes\n",
    "#The next step is to create a tree hierarchy.\n",
    "ipt.getclasstree(ipt.getmro(BaseException))\n",
    "#function call\n",
    "tree_class(BaseException)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81e1f68e-3b41-4f2e-a1f9-c9db9ec53aeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: What errors are defined in ArithmeticError class? Explain any two with example.\n",
    "Answer:\n",
    "Arithmetic Error:\n",
    "The arthemetic error occurs when an error is encountered during numeric calculations in python. This includes Zerodivision Error and Floating point error.\n",
    "In addition, zero division error is raised when you divide a numeric value by zero.\n",
    "ArithemiticError types in python include:\n",
    "1). OverFlowError\n",
    "2). ZeroDivisonError\n",
    "\n",
    "1). OverFlowError:\n",
    "An overflow error, in general, is as its name suggets which means overflow itself defines an extra part, therefore in python also this occurs when an obtained value or result\n",
    "is larger than the declared opreation or data type in the program then this throws an overflow error indicating the value is exceeding the given or declared limit value.\n",
    "\n",
    "Example to Implement Python OverflowError:\n",
    "    \n",
    "print(\"simple program for showing overflow error\")\n",
    "print(\"\\n\")\n",
    "import math\n",
    "print(\"The exponential value is\")\n",
    "print(math.exp(1000))\n",
    "\n",
    "Explanation: In the above program, we can see that we are declaring math module and using to using to calculate exponential value such as exp(1000) which means e^x  here x \n",
    "value is 1000 and e value is 2.7 whaere when are trying to calculate this it will give value as a result which is double and it cannot print result, therefore, it gives an overflow \n",
    "error as seen in the above program which says it is out of range because the x value is 1000 which results give the value which is out of range or double to store the value and\n",
    "print it.\n",
    "\n",
    "2). ZeroDivisionError:\n",
    "A zeroDivisionError occurs in python when a number is attempted to be divided by zero. since divison by zero is not allowed in mathematics, attempting this in python code\n",
    "raise a ZeroDivisionError.\n",
    "\n",
    "Example: Python ZeroDivisionError Example\n",
    "here's an example of a python ZeroDivisionError thrown due to division by zero:\n",
    "a = 10\n",
    "b = 0\n",
    "print(a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b82fa2e0-5ade-4bba-ad89-d307ef4dbfca",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: Why LookupError class is used? explain with an example KeyError and IndexError.\n",
    "\n",
    "Answer: lookupError exception is the Base class for errors raised when something cannot be found. the base class for the exceptions that are raised when a key or index used on a\n",
    "mapping or sequence is invalid: IndexError, KeyError.\n",
    "\n",
    "IndexError:\n",
    "Indexerror is an exception in python that occurs when we try to access an element from a list or tuple from an index that is not present in the list.\n",
    "For example, we have a \n",
    "list or tuple from an index that is not present in the list.For example, we have a list of 10 elements, the index is from 0 to 9.\n",
    "if we try to access an element an index 10 or 11 or more, it will cause the program to raise IndexError with the \n",
    "message \" IndexError: list index out of range\"\n",
    "\n",
    "example:\n",
    "myList = [1,2,3,4,5,6,7,8,9,10]\n",
    "print(\"The list is:\", myList)\n",
    "index = 10\n",
    "element = myList[index]\n",
    "print(\"element at index {} is {}\". format(index, element))\n",
    "\n",
    "\n",
    "KeyError:\n",
    "A python KeyError exception is what is raised when you try to access a key that is not in a dictionary(dict).\n",
    "python offical documentation says that the KeyError is raised when a mapping key is accessed and is not found in the mapping. A mapping is a data structure that maps one se\n",
    "of values to another.\n",
    "\n",
    "Example:\n",
    "#creating a dictionary\n",
    "subjects = {'sree': 'maths',\n",
    "            'ram': 'science,\n",
    "            'shyam': 'science',\n",
    "            'abdul': 'hindi'}\n",
    "#printing the subject of fharan\n",
    "print(subjects['fharan'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4704ab8b-14c2-4110-baa3-eaac2206ae86",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: Expalin the importError. What is not ModuleNotFoundError?\n",
    "\n",
    "Answer: \n",
    "# ImportError:\n",
    "when we want to include the module contents in the program then we have to import these specific modules in the program. so to do this we use \"import\" keyword such as import \n",
    "statement with the module name. when writting this statement and then specified module is not written properly or the imported module is not found in the python libary then the \n",
    "python interpreter throws an error known as ImportError.\n",
    "\n",
    "There are two conditions when the ImportError will be raised. They are:\n",
    "    1). If the module does not exist.\n",
    "    2). If we are trying to import submodule from the module\n",
    "\n",
    "\n",
    "# ModuleNotFoundError:\n",
    "when you try to import a module in a python file, python tries to resolve this module in a python file, python tries to resolve this module in several ways. sometimes,\n",
    "python throws the ModuleNotFoundError .\n",
    "As the name implies, this error occurs when you are trying to access or use a module that cannot be found. In the case of the title, the \"module named Python\" cannot be found.\n",
    "\n",
    "Python here can be any module. here is an error when I try to import a numpys module that cannot be found:\n",
    "    import numpys as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "963bf0d2-fcaf-4bf8-826b-feecfc33b652",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question: List down some best practices for exception handling in python.\n",
    "Answer: \n",
    "10 Python exception Handling Best Practices:\n",
    "    \n",
    "1).Use Exceptions for Exceptional cases\n",
    "2). Do not Swallow the Exception\n",
    "3).Catch Specific Exceptions\n",
    "4). Always clean up Resources in a Finally block\n",
    "5). Avoid Raising Generic Exceptions\n",
    "6). Raise custom Exceptions\n",
    "7). Define your own Exception Hierarchy\n",
    "8). Document All Exceptions Thrown by a function\n",
    "9). Provide contextual Information When Raising an exception"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6dd966e2-fd33-483b-a070-519b0eca0f2e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8def3d95-5d95-49ac-8fcb-0c548794681d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
